name: List SFTP Directory

on:
  workflow_dispatch:

jobs:
  list:
    runs-on: ubuntu-latest

    steps:
      - name: Add SFTP host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H iad1-shared-b8-11.dreamhost.com >> ~/.ssh/known_hosts

      - name: List objo_binaries
        env:
          USERNAME: ${{ secrets.BINARIES_USER }}
          PASSWORD: ${{ secrets.BINARIES_PASSWORD }}
        run: |
          curl --fail --show-error --list-only \
            -u "$USERNAME:$PASSWORD" \
            "sftp://iad1-shared-b8-11.dreamhost.com/home/$USERNAME/objo.adamov.rs/objo_binaries/"
            