name: Publish macOS Objo Application

on:
  workflow_dispatch:

jobs:
  publish-macos:
    uses: madamov/ObjoPublisher/.github/workflows/publish_objo_macos.yml@main

    with:
      solution-file: MyGreatApp.objosln
      project-file: Projects/MyGreatApp/project.json
      application-name: MyGreatApp
      artifact-name: mygreatapp-macos-publish
      apple-notary-profile: mygreatapp-notarization

      # Optional. Leave this out to detect the latest version.
      # objo-version: 26.7.1

    secrets:
      apple-certificate: ${{ secrets.APPLE_CERTIFICATE }}
      apple-certificate-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
      apple-app-specific-password: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
      objo-license: ${{ secrets.OBJO_LICENSE }}
      apple-certificate-name: ${{ secrets.APPLE_CERTIFICATE_NAME }}
      apple-team-id: ${{ secrets.APPLE_TEAM_ID }}
      apple-id: ${{ secrets.APPLE_ID }}
      