name: ObjoPublisher for Linux

on:
  workflow_dispatch:

jobs:
  publish-linux:
    uses: madamov/ObjoPublisher/.github/workflows/publish_objo_linux.yml@main

    with:
      solution-file: MyGreatApp.objosln
      project-file: Projects/MyGreatApp/project.json
      application-name: MyGreatApp
      output-directory: Publish
      targets: "linux-x64"
      artifact-name: mygreatapp-linux-publish

    secrets:
      objo-license: ${{ secrets.OBJO_LICENSE }}
      
